version: '2'
services:
  cups:
    build: .
    privileged: true
    ports:
      - "631:631"
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /dev/bus/usb:/dev/bus/usb
#      - ./data/log/:/var/log/cups/
#      - ./data/spool/:/var/spool/cups/
#      - ./data/etc/:/etc/cups
