version: '2.0'
services:
  cups:
    build:
       context: cups
       args:
         - CUPS_PASSWORD=print
    privileged: true
    ports:
      - 6631:631
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /dev/bus/usb:/dev/bus/usb

  gcp:
    build:
       context: gcp
       args:
         - GCP_SHARE_SCOPE=xxxx
         - GCP_NAME=raspberry
    privileged: true
    links:
      - cups
    volumes:
      - /var/run/dbus:/var/run/dbus
