version: '2.0'
services:
  cups:
    build:
       context: cups
    privileged: true
    ports:
      - 6631:631
    expose:
      - 631
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /dev/bus/usb:/dev/bus/usb
    env_file: .env

  gcp:
    build:
       context: gcp
    env_file: .env
    links:
      - cups
    environment:
      - CUPS_SERVER=cups
