version: '2'
services:
  cups:
    container_name: cups
    build: .
    privileged: true
    ports:
      - "631:631"
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /dev/bus/usb:/dev/bus/usb
    args:
      - share-scope
      - proxy-name:raspberry
      - admin-password
